_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "pretrained_models/R-50.pkl"
  BACKBONE:
    NAME: "build_search_backbone"
  SEARCH:
    BACKBONE_ARGS:
        [[-1, 1, Conv_search_merge,         [64, [[3,1],[5,1],[7,1]], [0.5,0.75,1.0], 2, {'gumbel_channel':True, 'id': 'res1'}]],   # 0-P1/2
        [-1, 1, Down_sampling_search_merge, [128, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], 2, {'search_c2': [0.75, 1.0], 'gumbel_channel':True}]],  # 1-P2/4
        [-1, 3, C3_search_merge,            [128, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], {'search_c2': [0.75, 1.0], 'gumbel_channel':True, 'id': 'res2'}]],
        [-1, 1, Down_sampling_search_merge, [256, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], 2, {'search_c2': [0.75, 1.0], 'gumbel_channel':True}]],  # 3-P3/8
        [-1, 9, C3_search_merge,            [256, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], {'search_c2': [0.75, 1.0], 'gumbel_channel':True, 'id': 'res3'}]],
        [-1, 1, Down_sampling_search_merge, [512, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], 2, {'search_c2': [0.75, 1.0], 'gumbel_channel':True}]],  # 5-P4/16
        [-1, 9, C3_search_merge,            [512, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], {'search_c2': [0.75, 1.0], 'gumbel_channel':True, 'id': 'res4'}]],
        [-1, 1, Down_sampling_search_merge, [1024, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], 2, {'search_c2': [0.75, 1.0], 'gumbel_channel':True}]],  # 7-P5/32
        [-1, 9, C3_search_merge,            [1024, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], {'search_c2': [0.75, 1.0], 'gumbel_channel':True, 'id': 'res5'}]],
        ]
OUTPUT_DIR: "output/sparse_inst_search"
