_BASE_: "Base-SparseInst.yaml"
MODEL:
  BACKBONE:
    NAME: "build_search_backbone"
  MODEL:
    BACKBONE:
      [[-1, 1, Focus, [64, 3, {}]],  # 0-P1/2
      [-1, 1, Conv_search_merge, [128, [[1,1],[3,1],[5,1],[3,2]], [0.5,0.75,1.0], 2, {'gumbel_channel':True, 'id': 'res2'}]],  # 1-P2/4
      [-1, 3, C3_search_merge, [128, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], {'search_c2': [0.75, 1.0], 'gumbel_channel':True}]],
      [-1, 1, Conv_search_merge, [256, [[1,1],[3,1],[5,1],[3,2]], [0.5,0.75,1.0], 2, {'gumbel_channel':True, 'id': 'res3'}]],  # 3-P3/8
      [-1, 9, C3_search_merge, [256, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], {'search_c2': [0.75, 1.0], 'gumbel_channel':True}]],
      [-1, 1, Conv_search_merge, [512, [[1,1],[3,1],[5,1],[3,2]], [0.5,0.75,1.0], 2, {'gumbel_channel':True, 'id': 'res4'}]],  # 5-P4/16
      [-1, 9, C3_search_merge, [512, [[3,1],[5,1],[3,2]], [0.5,0.75,1.0], {'search_c2': [0.75, 1.0], 'gumbel_channel':True}]],
      [-1, 1, Conv_search_merge, [1024, [[1,1],[3,1],[5,1],[3,2]], [0.5,0.75,1.0], 2, {'gumbel_channel':True, 'id': 'res5'}]],  # 7-P5/32
      [-1, 1, SPP_search, [1024, [5, 9, 13], {}]],
      ]
OUTPUT_DIR: "output/sparse_inst_search"
